---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ice-image-builder
  namespace: build
rules:
  - apiGroups:
      - ''
      - build.openshift.io
    resources:
      - builds
      - buildconfigs
    verbs:
      - '*'
  - apiGroups:
      - ''
      - image.openshift.io
    resources:
      - images
      - imagestreams
      - imagestreamtags
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ice-image-builder
  namespace: build
rules:
  - apiGroups:
      - ''
      - build.openshift.io
    resources:
      - builds
      - buildconfigs
    verbs:
      - '*'
  - apiGroups:
      - ''
      - image.openshift.io
    resources:
      - images
      - imagestreams
      - imagestreamtags
    verbs:
      - '*'
