name: OpenShift CLI Setup
description: Installs and configures the OpenShift CLI (oc)
inputs:
  openshift-server-api-url:
    description: The URL to the OpenShift cluster's API
    required: true
  openshift-auth-token:
    description: The authentication token to use
runs:
  using: composite
  steps:
    # At the time of writing, oc is already installed in Ubuntu runners, per
    # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#cli-tools
    - name: Install oc
      if: ${{ !!env.ACT }}
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: '4'
    - name: Log into the cluster
      uses: icemobilelab/github-actions-pipeline/actions/login-to-cluster@v1
      with:
        openshift-server-api-url: ${{ inputs.openshift-server-api-url }}
        openshift-auth-token: ${{ inputs.openshift-auth-token }}
