name: 3scale deployment
description: |
  Deploys an OpenAPI (Swagger) spec to 3scale. This action will take its configuration from the `threeScale`
  property of the calling repository's `package.json`. e.g.:
    "threeScale": {
        "systemName": "github-actions",
        "publicBasePath": "/github/actions",
        "clusters": [
            {
                "name": "ARO_ACC_WESTEUROPE"
            },
            {
                "name": "ARO_PRD_WESTEUROPE"
            }
        ]
    }
inputs:
  swagger-directory:
    description: >
      The path to the directory within the calling repository that contains the OpenAPI files.
      Defaults to `docs/swagger`
    default: docs/swagger
    required: false
  internal-spec-file:
    description: Name of the OpenAPI internal spec file. Defaults to `<repo-name>.yml`
    required: false
  public-spec-file:
    description: Name of the OpenAPI public spec file. Defaults to `public.yml`
    default: public.yml
    required: false
  cluster:
    description: |
      The cluster to deploy to. One of:
        - TST
        - ARO_ACC_CANADACENTRAL
        - ARO_PRD_CANADACENTRAL
        - ARO_PRD_CANADACENTRAL2
        - ARO_ACC_WESTEUROPE
        - ARO_PRD_WESTEUROPE
    required: false
    default: TST
runs:
  using: node16
  main: dist/index.mjs
