name: 'Run unit, lint and sonar checks'
inputs:
    fetch-depth:
        required: false
        description: 'Number of commits to fetch during checkout. 0 indicates all history for all branches and tags.'
        default: '1'
    ref:  
        required: false
        description: 'The branch, tag or SHA to checkout. When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event.  Otherwise, uses the default branch.'
        default: '1'  
    pat-token:
        required: false
        description: 'Personal access token (PAT) used to fetch the repository.'
        default: ${{ github.token }}
    icemobile-pat-token:
        required: false
        description: 'PAT with access to all internal IceMobile repos'
    sonar-token:
        required: true
        description: 'Pass ${{ secrets.SONAR_TOKEN }} here'

runs:
  using: 'composite'
  steps:
  
    - name: Checkout the commit
      uses: actions/checkout@v2
      with:
          fetch-depth: ${{ inputs.fetch-depth }}
          fetch-depth: ${{ inputs.ref }}
          token: ${{ inputs.pat-token }}

    - name: Set up Node
        uses: actions/setup-node@v2
        with:
            node-version: 14

    - name: Reconfigure Git authentication
      run: |
        git config --global --add url."https://${{ inputs.icemobile-pat-token }}:x-oauth-basic@github.com/".insteadOf "ssh://git@github.com/"
        git config --global --add url."https://${{ inputs.icemobile-pat-token }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

    - name: Run npm ci
      run: npm ci
      
    - name: Run linter
      run: npm run lint

    - name: Run unit tests  
      run: npm run unit-test
      env:
        CI: true

    # Run Sonar check as a step and not as a separate job
    # in order to collect coverage data generated on previous (npm run test) step.
    # To see more sonar settings, have a look at sonar-project.properties file
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.6
      env:
        GITHUB_TOKEN: ${{ github.token }}
        SONAR_TOKEN: ${{ inputs.sonar-token }} 