name: 'Run unit, lint and sonar checks'
inputs:
    fetch-depth:
        required: false
        description: 'Number of commits to fetch during checkout. 0 indicates all history for all branches and tags.'
        default: '1'
    ref:  
        required: false
        description: 'The branch, tag or SHA to checkout. When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event.  Otherwise, uses the default branch.'
    pat-token:
        required: false
        description: 'Personal access token (PAT) used to fetch the repository.'
        default: ${{ github.token }}
    icemobile-pat-token:
        required: false
        description: 'PAT with access to all internal IceMobile repos'
    sonar-token:
        required: true
        description: 'Pass secrets.SONAR_TOKEN here'
    sonar-sources:
        required: false
        description: Sourse folder to scan
        default: 'lib/util'

runs:
  using: 'composite'
  steps:
    - name: Checkout the commit
      uses: actions/checkout@v2
      with:
          fetch-depth: ${{ inputs.fetch-depth }}
          ref: ${{ inputs.ref }}
          persist-credentials: false

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
          node-version: 14

    - name: Reconfigure Git authentication
      shell: bash
      run: |
        git config --global --add url."https://${{ inputs.icemobile-pat-token }}:x-oauth-basic@github.com/".insteadOf "ssh://git@github.com/"
        git config --global --add url."https://${{ inputs.icemobile-pat-token }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

    - name: Run npm ci
      shell: bash
      run: npm ci
      
    - name: Run linter
      shell: bash
      run: npm run lint

    - name: Run unit tests
      shell: bash
      run: npm run unit-test
      env:
        CI: true

    - name: Create sonar properties file
      shell: bash
      run: |
        cat > sonar-project.properties << ENDOFFILE
        sonar.eslint.eslintconfigpath=.eslintrc
        sonar.host.url=https://sonarcloud.io
        sonar.inclusions=**/*.js
        sonar.javascript.lcov.reportPaths=coverage/lcov.info
        sonar.projectKey=${{ github.repository }}
        sonar.sourceEncoding=UTF-8
        sonar.sources=${{ inputs.sonar-sources }}
        sonar.organization=icemobilelab
        ENDOFFILE

    - name: Read file contents
      shell: bash
      run: cat sonar-project.properties
        

    # Run Sonar check as a step and not as a separate job
    # in order to collect coverage data generated on previous (npm run test) step.
    # To see more sonar settings, have a look at sonar-project.properties file
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.6
      env:
        GITHUB_TOKEN: ${{ inputs.pat-token}}
        SONAR_TOKEN: ${{ inputs.sonar-token }} 