name: 'Run unit, lint and sonar checks'
description: 'Run unit, lint and sonar checks'
inputs:
    minimum-code-coverage:
        required: false
        description: The minimum percentage of code that must be covered to succeed. If unset, coverage isn't checked
runs:
  using: 'composite'
  steps:
    - name: Install node
      uses: icemobilelab/github-actions-pipeline/actions/install-node@v1

    - name: Run npm ci
      shell: bash
      run: npm ci

    - name: Run linter
      uses: icemobilelab/github-actions-pipeline/actions/run-linter@v1

    - name: Run unit tests
      uses: icemobilelab/github-actions-pipeline/actions/run-unit-tests@v1
      with:
        minimum-code-coverage: ${{ inputs.minimum-code-coverage }}

    - name: Run sonarqube
      uses: icemobilelab/github-actions-pipeline/actions/run-sonarqube@v1
