name: Master Pipeline
run-name: Master Pipeline
on:
  push:
    branches: # pick whichever is your repository's main branch
      - master
      - main
      - develop
  workflow_dispatch:
    inputs:
      deployment-namespace:
        type: string
        description: The namespace to which to deploy the project
        required: true
        # Change 'loyalty-tst' to the namespace where your project needs to be deployed
        default: loyalty-tst
jobs:
  master-pipeline:
    name: Master Pipeline
    uses: icemobilelab/github-actions-pipeline/.github/workflows/reusable-master-pipeline.yml@v1
    secrets: inherit
    with:
      # Change 'loyalty-tst' to the namespace where your project needs to be deployed
      deployment-namespace: ${{ inputs.deployment-namespace || 'loyalty-tst' }}
      # Change this to your minimum required code coverage percentage. Unset or 0 means no check is done
      minimum-code-coverage: 95
      # The following are the default values for the 3scale deployment action. Uncomment and change if needed
      # swagger-directory: docs/swagger
      # internal-spec-file: <your-repo-name>.yml
      # public-spec-file: public.yml
      # cluster: TST
