name: Create Integration Test Namespace
description: >
  Creates a new namespace used for integration tests. **Requires a
  previously configured OpenShift CLI (`oc`)**
outputs:
  testing-namespace:
    description: The namespace that was created
runs:
  using: node16
  main: dist/index.mjs
  # steps:
  #   - name: Create NS
  #     id: create
  #     shell: bash
  #     run: |
  #       _projectName="$(echo -n "$GITHUB_REPOSITORY" | awk -F/ '{ print $2 }')"
  #       ns="test-${_projectName}-${GITHUB_SHA:0:8}-p4vl0s7r1n9"
  #       echo "ns=${ns}" >> $GITHUB_OUTPUT

  #       oc delete project "${ns}" --wait || true

  #       oc new-project "${ns}"
  #       oc adm policy add-role-to-group edit adm_aro_developers -n "${ns}"
  #       oc adm policy add-role-to-group edit adm_aro_testers -n "${ns}"
  #       oc adm policy add-role-to-group edit adm_aro_superdevelopers -n "${ns}"
  #       oc adm policy add-role-to-group system:image-puller "system:serviceaccounts:${ns}" -n cicd
