name: Create Integration Test Namespace
description: >
  Creates a new namespace used for integration tests. **Requires a
  previously configured OpenShift CLI (`oc`)**
outputs:
  testing-namespace:
    description: The namespace that was created
runs:
  using: node16
  main: dist/index.mjs
