name: Run Integration Tests
description: Runs all integration tests configured in the project
inputs:
  namespace:
    description: The namespace to where the project is deployed
    required: true
runs:
  using: node16
  main: dist/index.mjs
